export const navDataLists = [
  {
    imgLink: "https://a0.muscache.com/pictures/7630c83f-96a8-4232-9a10-0398661e2e6f.jpg",
    name: "Rooms"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/3fb523a0-b622-4368-8142-b5e03df7549b.jpg",
    name: "Amazing pools"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/3726d94b-534a-42b8-bca0-a0304d912260.jpg",
    name: "Trending"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/5ed8f7c7-2e1f-43a8-9a39-4edfc81a3325.jpg",
    name: "Bed & breakfasts"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/8b44f770-7156-4c7b-b4d3-d92549c8652f.jpg",
    name: "Arctic"
  },

  {
    imgLink: "https://a0.muscache.com/pictures/e4b12c1b-409b-4cb6-a674-7c1284449f6e.jpg",
    name: "Cycladic homes"
  },

  {
    imgLink: "https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg",
    name: "Amazing views"
  },

  {
    imgLink: "https://a0.muscache.com/pictures/d721318f-4752-417d-b4fa-77da3cbc3269.jpg",
    name: "Towers"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/78ba8486-6ba6-4a43-a56d-f556189193da.jpg",
    name: "Mansions"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/ed8b9e47-609b-44c2-9768-33e6a22eccb2.jpg",
    name: "Iconic cities"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/ddd13204-a5ae-4532-898c-2e595b1bb15f.jpg",
    name: "Chef's kitchens"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/c5a4f6fc-c92c-4ae8-87dd-57f1ff1b89a6.jpg",
    name: "OMG"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/8eccb972-4bd6-43c5-ac83-27822c0d3dcd.jpg",
    name: "Grand pianos"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/50861fca-582c-4bcc-89d3-857fb7ca6528.jpg",
    name: "Design"
  },
  {
    imgLink: "https://a0.muscache.com/pictures/7ff6e4a1-51b4-4671-bc9a-6f523f196c61.jpg",
    name: "Riads"
  },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/c9157d0a-98fe-4516-af81-44022118fbc7.jpg",
  //   name: "Dammusi"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/89faf9ae-bbbc-4bc4-aecd-cc15bf36cbca.jpg",
  //   name: "Domes"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/f0c5ca0f-5aa0-4fe5-b38d-654264bacddf.jpg",
  //   name: "Play"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/ee9e2a40-ffac-4db9-9080-b351efc3cfc4.jpg",
  //   name: "Tropical"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/6ad4bd95-f086-437d-97e3-14d12155ddfe.jpg",
  //   name: "Countryside"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/248f85bf-e35e-4dc3-a9a1-e1dbff9a3db4.jpg",
  //   name: "Top of the world"
  // },
  // {
  //   imgLink: "https://a0.muscache.com/pictures/732edad8-3ae0-49a8-a451-29a8010dcc0c.jpg",
  //   name: "Cabins"
  // },
];

const images = [
  'https://plus.unsplash.com/premium_photo-1683296357476-db69c5ded3a7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YWlyYm5ifGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YWlyYm5ifGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YWlyYm5ifGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1614607242094-b1b2cf769ff3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60'
]

const images2 = [
  'https://images.unsplash.com/photo-1620332372374-f108c53d2e03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1550355191-aa8a80b41353?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1590725121839-892b458a74fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1601919297600-8ffbfd160d2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1583719445062-62d0d98c4d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60'
]

const images3 = [
'https://images.unsplash.com/photo-1573790285658-87d7586eec7d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzB8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
'https://plus.unsplash.com/premium_photo-1684445034959-b3faeb4597d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
'https://plus.unsplash.com/premium_photo-1684445034552-b042da57f310?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
'https://images.unsplash.com/photo-1602081850531-344675d48d0f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
'https://images.unsplash.com/photo-1599202937077-3f7cdc53f2e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60'
];


const images4 = [
  'https://images.unsplash.com/photo-1601919297600-8ffbfd160d2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1583719445062-62d0d98c4d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://plus.unsplash.com/premium_photo-1684445034959-b3faeb4597d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://plus.unsplash.com/premium_photo-1684445034552-b042da57f310?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
]

const image5 = [
  'https://plus.unsplash.com/premium_photo-1686167986315-a373b13946c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjF8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60',
  'https://images.unsplash.com/photo-1635286756403-9d401732a2e0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjR8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60',
  'https://images.unsplash.com/photo-1604809173867-6b6aef726a41?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODJ8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60'
];


const images1 = [
  'https://images.unsplash.com/photo-1604809173867-6b6aef726a41?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODJ8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60',
  'https://plus.unsplash.com/premium_photo-1684445034552-b042da57f310?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1599202937077-3f7cdc53f2e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',
  'https://images.unsplash.com/photo-1583719445062-62d0d98c4d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGFpcmJuYnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60'

]

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

export const cardDatas = [
  {
    name: 'Ngaparou, Senegal',
    images: images1,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms"
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Rooms",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing pools",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Trending",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Bed & breakfasts",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Bed & breakfasts",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Bed & breakfasts",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Bed & breakfasts",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Cycladic homes",
  },
  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Cycladic homes",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images1,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Cycladic homes",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Cycladic homes",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing views",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing views",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing views",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing views",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Amazing views",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Towers",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Towers",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Towers",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Towers",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Towers",
  },

  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Mansions",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Mansions",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Mansions",
  },

  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Iconic cities",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Iconic cities",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Iconic cities",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Arctic",
  },
  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Chef's kitchens",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Chef's kitchens",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images1,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Chef's kitchens",
  },

  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "OMG",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "OMG",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Grand pianos",
  },
  {

    name: 'Ngaparou, Senegal',
    images: images2,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Grand pianos",
  },
  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Grand pianos",
  },

  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Design",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images1,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Design",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images3,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Design",
  },

  {
    name: 'Ngaparou, Senegal',
    images: image5,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Riads",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images4,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Riads",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Riads",
  },
  {
    name: 'Ngaparou, Senegal',
    images: images1,
    host: '',
    availableFor: 'Spe 4 - 11',
    rating: '4.86',
    like: false,
    distance: '2,403 kilometers away',
    filter: "Riads",
  },
];
